server:
  port: 8080

spring:
  application:
    name: movies
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:moviesofyear
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

path-file: src/main/resources/movielist.csv

